name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        python-version: [3.9]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Node.js Setup & Testing for Transaction Service
    - name: Setup Node.js for transaction-service
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies for Transaction Service
      run: |
        cd transaction-service
        npm install
    - name: Run Tests for Transaction Service
      run: |
        cd transaction-service
        npm test

    # Node.js Setup & Testing for Fraud Analysis Service
    - name: Setup Node.js for fraud-analysis-service
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies for Fraud Analysis Service
      run: |
        cd fraud-analysis-service
        npm install
    - name: Run Tests for Fraud Analysis Service
      run: |
        cd fraud-analysis-service
        npm test

    # Python Setup & Testing for ML Component
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies for ML Component
      run: |
        cd ml-component
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Run Tests for ML Component
      run: |
        cd ml-component
        source venv/bin/activate
        python -m unittest discover

    # (Optional) Terraform Validation
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11
    - name: Terraform Init and Validate
      working-directory: terraform
      run: |
        terraform init
        terraform validate
