name: ML Component CI/CD

on:
  push:
    paths:
      - 'ml-component/**'
      - '.github/workflows/ml-component.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'ml-component/**'
      - '.github/workflows/ml-component.yml'
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: ml-component/requirements.txt

    - name: Install dependencies
      working-directory: ./ml-component
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Code formatting check
      working-directory: ./ml-component
      run: |
        black --check .
        isort --check-only .

    - name: Type checking
      working-directory: ./ml-component
      run: mypy .

    - name: Run tests
      working-directory: ./ml-component
      run: pytest
